<?php

/**
 * @var $block \GFNL\PixQrCode\Block\Info\PixQrCode
 */
$order = $block->getOrder();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>
<?php if ($block->getInfo()->getAdditionalInformation()) : ?>
    <?php if ($block->getPayloadPix()) : ?>
        <br/>
        <p><?= $block->escapeHtml(__('Digitable line: %1', $block->getPayloadPix())) ?></p>
        <br/>
        <p>Após efetuar o pagamento, nos encaminhe seu comprovante para o e-mail: <a href="mailto:<?=
            $block->getEmailForConfirmation() ?>&subject=<?= $order->getIncrementId() ?>"><?= $block->getEmailForConfirmation() ?></a>
            junto com o seu
            número do pedido: #<?= $order->getIncrementId() ?>.
        </p>
    <?php endif; ?>
<?php endif; ?>
