<?php

/**
 * @var $block \GFNL\PixQrCode\Block\Info\PixQrCode
 */
$order = $block->getOrder();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>
<?php if ($block->getInfo()->getAdditionalInformation()) : ?>
    <?php if ($block->getPayloadPix()) : ?>
        <div class="pix-payment order-view">
            <span class="title"><?= __("Copie o código Pix abaixo e cole em seu app  de pagamento.") ?></span>
            <div class="pix-code">
                <span><?= $block->getPayloadPix() ?></span>
            </div>
            <div class="instruction">
                <span><?= __("Instruções após pagamento") ?></span>
                <p><?= __("Após efetuar o pagamento, por favor, nos envie o comprovante para o e-mail: <a href='mailto:%1&subject=Comporvante de pagamento para o pedido: #%2'>%1</a> junto com seu número de pedido: #%2", $block->getEmailForConfirmation(), $order->getIncrementId()) ?></p>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
