<?php

/**
 * @var $block \GFNL\PixQrCode\Block\Info\PixQrCode
 */
$order = $block->getOrder();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>
<?php if ($block->getInfo()->getAdditionalInformation()) : ?>
    <?php if ($block->getPayloadPix()) : ?>
        <div class="pix-payment order-view">
            <span class="title"><?= __("Copie o código Pix abaixo e cole em seu app  de pagamento.") ?></span>
            <div class="pix-code">
                <span><?= $block->getPayloadPix() ?></span>
            </div>
            <div class="instruction">
                <span><?= __("Instruções após pagamento") ?></span>
                <?php if ($block->getTypeOfProofPayment() === 'by_email'): ?>
                    <p>
                        <?= __("Após efetuar o pagamento, por favor, nos envie o comprovante para o e-mail: <a href='mailto:%1&subject=Comporvante de pagamento para o pedido: #%2'>%1</a> junto com seu número de pedido: #%2", $block->getEmailForConfirmation(), $order->getIncrementId()) ?>
                    </p>
                <?php endif; ?>
                <?php if ($block->getTypeOfProofPayment() === 'by_whatsapp'): ?>
                    <p>
                        <?= __("Após efetuar o pagamento, por favor, nos envie o comprovante pelo número de WhatsApp <a href='https://api.whatsapp.com/send?phone=%1&text=Segue o comprovante para o pedido: %2' target='_blank'>%1</a>.", $block->getWhastappNumber(), $order->getIncrementId()) ?>
                    </p>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
