<?php
/**
 * @var $block \GFNL\PixQrCode\Block\Success
 * @var $order \Magento\Sales\Model\Order
 */

$order = $block->getOrder();
$paymentInfo = $order->getPayment()->getAdditionalInformation();

$qrcodepix = $paymentInfo['qrcode'] ?? '';
$payloadPix = $paymentInfo['payload_pix'] ?? '';
?>
<?php if ($order->getPayment()->getMethod() === 'gfnl_pixqrcode'): ?>
    <div class="pix-payment checkout">
        <div class="payment-info">
            <div class="qrcode">
                <span><?= __('Escanei o Qr Code com seu celular') ?></span>
                <img src="<?= $qrcodepix ?>" alt="qrcode para pagamento pix"/>
            </div>
            <span class="separate-text">ou</span>
            <div class="pixcode">
                <span class="title"><?= __('Copie o código Pix abaixo e cole em seu app de pagamento.') ?></span>
                <div class="pix-code">
                    <textarea readonly><?= $payloadPix ?></textarea>
                </div>
                <button id="clickToCopy" class="action-primary">
                    <?= __('Copiar Código Pix') ?>
                </button>
                <span id="message"></span>
            </div>
        </div>
        <div class="separate-bar"></div>
        <div class="instruction">
            <span><?= __('Instruções após pagamento') ?></span>
            <?php if ($block->getTypeOfProofPayment() === 'by_email'): ?>
                <p>
                    <?= __("Após efetuar o pagamento, por favor, nos envie o comprovante para o e-mail: <a href='mailto:%1&subject=Comporvante de pagamento para o pedido: #%2'>%1</a> junto com seu número de pedido: #%2", $block->getEmailForConfirmation(), $order->getIncrementId()) ?>
                </p>
            <?php endif; ?>
            <?php if ($block->getTypeOfProofPayment() === 'by_whatsapp'): ?>
                <p>
                    <?= __("Após efetuar o pagamento, por favor, nos envie o comprovante pelo número de WhatsApp <a href='https://api.whatsapp.com/send?phone=%1&text=Segue o comprovante para o pedido: %2' target='_blank'>%1</a>.", $block->getWhastappNumber(), $order->getIncrementId()) ?>
                </p>
            <?php endif; ?>
        </div>
    </div>

    <script>
        const clicktoCopy = document.querySelector("#clickToCopy");

        clicktoCopy.addEventListener('click', () => {
            const chavePix = "<?=$payloadPix?>";
            navigator.clipboard.writeText(chavePix);
            document.querySelector('#message').innerHTML = "<?= __("Chave pix copiada com sucesso!") ?>";
            setTimeout(function () {
                document.querySelector('#message').innerHTML = "";
            }, 3000)
        });
    </script>
<?php endif; ?>
