<?php

/**
 * @var $block \GFNL\PixQrCode\Block\Info\PixQrCode
 */
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>
<?php if ($block->getInfo()->getAdditionalInformation()) : ?>
    <?php if ($block->getPayloadPix()) : ?>
        <div class="pix-payment">
            <span><?= __("Copie o código Pix abaixo e cole em seu app  de pagamento.") ?></span>
            <div class="pix-code">
                <span><?= $block->getPayloadPix() ?></span>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
